spring:
  application:
    name: Tenant-Management-Service

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: manager
    url: jdbc:postgresql://localhost:5432/tenantManagementService

  kafka:
    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: user-mgmt-group
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: '*'
    admin:
      auto-create: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083
springdoc:
  api-docs:
    path: /api-docs




